### ISSUE TITLE
Setting of parameters for Object Loss

### ISSUE THREAD

**Issue by dhgras** [OceanYing/OmniSeg3D-GS#1]
Hi, thank you for your excellent work!

I am trying to apply this work to my own dataset, which contains over 1000 rgb images with a resolution of around 2k. I have some doubts about the object loss:
1. When does the [average_flag](https://github.com/OceanYing/OmniSeg3D-GS/blob/a8eef6cb6ba58b53d4436be9c57748e054224fda/train.py#L103) need to be set to **True**?
2. How to adjust [clustersize](https://github.com/OceanYing/OmniSeg3D-GS/blob/a8eef6cb6ba58b53d4436be9c57748e054224fda/train.py#L106)/[batchsize](https://github.com/OceanYing/OmniSeg3D-GS/blob/a8eef6cb6ba58b53d4436be9c57748e054224fda/train.py#L113)?

Looking forward to your reply!

**Comment by OceanYing** [comment]
Hi, thanks for your interest in our work!

1. With [average_flag = False](https://github.com/OceanYing/OmniSeg3D-GS/blob/a8eef6cb6ba58b53d4436be9c57748e054224fda/train.py#L103), the sampled pixel number in each patch $p$ is proportional to the pixel-size of $p$. Since this sampling strategy may ignore the small patches, you can turn on the ```average_flag``` to sample the **same** number of pixels in each patch. This is a simple trial and we found ```average_flag = False``` performs better in most cases empirically. Therefore I leave the default setting as ```average_flag = False```.
2. Larger [clustersize](https://github.com/OceanYing/OmniSeg3D-GS/blob/a8eef6cb6ba58b53d4436be9c57748e054224fda/train.py#L106) / [batchsize](https://github.com/OceanYing/OmniSeg3D-GS/blob/a8eef6cb6ba58b53d4436be9c57748e054224fda/train.py#L113)  usually results in faster convergence since more pixels are taken into contrastive learning in each iteration. You can set the value depending on your GPU memory.
3. For your case, I would recommend the default setting (```average_flag = False```  and a large value of batchsize >=32768). We have tested on LERF and MIP360 datasets with this setting and it should work for you, too.

Feel free to contact me if you have further questions!

**Comment by dhgras** [comment]
Okay, I got it. Thank you for your reply!
