### ISSUE TITLE
Program is consuming tremendous amount of memory VRAM / VRAM

### ISSUE THREAD

**Issue by abrahamezzeddine** [OceanYing/OmniSeg3D-GS#3]
Hello,

This code is consuming tens of gigabytes of RAM and VRAM (more than 40GB of RAM and 35GB of VRAM). Any reason why? I used the "lowest" model and then it works fine... but using 35GB of VRAM is very high. Do we have to downsample the images perhaps?

Also,

python run_sam.py --ckpt_path {SAM_CKPT_PATH} --file_path {IMAGE_FOLDER} --gpu_id {GPU_ID}

gpu_id does not exist as an argument in the run_sam.py file.

Even during training, the program uses large amount of VRAM, any reason why? Nerfstudio uses around 5GB VRAM during training while this uses like 20GB VRAM. Please advice.

**Comment by OceanYing** [comment]
Hi, for the problem of memory consumption during running ```run_sam.py```, please refer to the answer in [Issue#2 of Omniseg3d](https://github.com/THU-luvision/OmniSeg3D/issues/2). 

For the training, compared to vanilla 3DGS, extra memory will be allocated to create a 16-dim feature vector for each Gaussian point, which cause higher memory consumption.

Besides, ```gpu_id``` is no longer used, which has been removed from the README.md, thanks a lot!

**Comment by abrahamezzeddine** [comment]
So now I managed to train this succesfully by downsampling the images quite a lot. But however, it seems that there is a lot of noise compared to those of yours.

See example below;

![00146](https://github.com/OceanYing/OmniSeg3D-GS/assets/142085947/1f190b89-7e01-401a-84b3-eaa168c1e789)
![00286](https://github.com/OceanYing/OmniSeg3D-GS/assets/142085947/9715e8e1-0598-4ebf-92b4-4ddd8e3b7dda)

Any suggestion on why the feature map is not clear?

**Comment by OceanYing** [comment]
I guess the noisy result is caused by poor geometry after the first stage of training. Since 3DGS renders pixels by integrating the Gaussian attributes along the camera rays, the blurry geometry will lead to noisy results after applying contrastive learning. For instance, let's say the point $p$ on the floor is occluded by a pillar, but since the geometry of the pillar is blurry, the point $p$ will still be sampled and weighs a lot during calculating contrastive loss. Finally, the pillar and the floor may have similar feature and cannot be separated.

There are some suggestions for you:
1. Choose the scene carefully (the scene with rich texture is easier than the one with specular surfaces).
2. Capture denser photos. Denser observations usually result in better geometry.
3. Try to improve the backbone of 3DGS (e.g. replace 3DGS with 2DGS, which enjoys better geometry).
